### ISSUE TITLE
Flonters + indrev breaks decoration in 1.16.2

### ISSUE THREAD

**Issue by ghost** [Yoghurt4C/Flonters#2]
Without both these mods, spawn looks like:
![image](https://user-images.githubusercontent.com/918422/91354249-b993f100-e7ec-11ea-9ac3-3f59ff65e327.png)

With these two mods, spawn looks like;
![image](https://user-images.githubusercontent.com/918422/91354333-e34d1800-e7ec-11ea-84d8-336c8f043bf9.png)

Removing Flonters or industrial revolution does generate decoration.
This also seems to impact ore gen by other mods that are not astromine.

**Comment by Yoghurt4C** [comment]
the current worldgen in flonters is a temporary measure until [this](https://github.com/FabricMC/fabric/pull/1036#issuecomment-679858506) gets pulled, does it *only* happen when both mods are present or when either of them is?

**Comment by ghost** [comment]
It only happens when both mods are present.

**Comment by ghost** [comment]
Here's the server log, in case it helps:
[latest.log](https://github.com/Yoghurt4C/Flonters/files/5132732/latest.log)

**Comment by ghost** [comment]
I have done some more testing.  Only removing Flonters from my pack doesn't solve the entire issue.  Though overworld biomedecoration works again, no ores besides astromine's are generated.

Removing industrial revolution and flonters from my pack does make all ores generate again.  I've picked this up with the indrev dev.

**Comment by ghost** [comment]
This got fixed on Industrial Revolution's end.  Thanks!
