### ISSUE TITLE
Conflicting with "Oh the Biomes You Go"

### ISSUE THREAD

**Issue by Misterboy64** [Yoghurt4C/Flonters#3]
Hello! i'm seeing that this mod is conflicting with Biomes you Go since the moment i put the mod in the modpack it just turns out that "byg" (abbreviated in "Biomes You Go") ends up with the launcher popping back up saying

`Error ; java.lang.RuntimeException : Could not execute entrypoint stage 'main' due to errors, provided by 'byg'! Exit Code: -1 `

now i know i might sound like a retard about Java Coding, but just telling you, is it a problem connected about this mod since this only happens when i put it?
thanks in advance
[2020-08-29-7.log.gz](https://github.com/Yoghurt4C/Flonters/files/5145488/2020-08-29-7.log.gz)

**Comment by Yoghurt4C** [comment]
🙏
