### ISSUE TITLE
[Compatibility] Use c:dyes and c:color_dyes tags

### ISSUE THREAD

**Issue by Trikzon** [Yoghurt4C/Flonters#4]
According to the [Fabric Wiki Tags List](https://www.fabricmc.net/wiki/tutorial:tags), a few mods are using the following tags instead of your tags. Your tags are only used by this mod.

| Flonters Tags | More Used Fabric Tags |
| - | - |
| `c:dye_any` | `c:dyes` |
| `c:dye_black` | `c:black_dyes` |
| `c:dye_blue` | `c:blue_dyes` |
| `c:dye_brown` | `c:brown_dyes` |
| `c:dye_cyan` | `c:cyan_dyes` |
| `c:dye_gray` | `c:gray_dyes` |
| `c:dye_green` | `c:green_dyes` |
| `c:dye_light_blue` | `c:light_blue_dyes` |
| `c:dye_light_gray` | `c:light_gray_dyes` |
| `c:dye_lime` | `c:lime_dyes` |
| `c:dye_magenta` | `c:magenta_dyes` |
| `c:dye_orange` | `c:orange_dyes` |
| `c:dye_pink` | `c:pink_dyes` |
| `c:dye_purple` | `c:purple_dyes` |
| `c:dye_red` | `c:red_dyes` |
| `c:dye_white` | `c:white_dyes` |
| `c:dye_yellow` | `c:yellow_dyes` |

**Comment by Yoghurt4C** [comment]
I wrote these jsons back when literally not a single soul wanted to be persuaded into using tags for dyes, with the counter-reasoning being "mojang standartized dyes as items so you don't need tags for them". will put this on my to-do list

**Comment by Yoghurt4C** [comment]
fixed in https://github.com/Yoghurt4C/Flonters/commit/46c1d15ae6c352660d3ab1c7d72e30173d7dccbb
