### ISSUE TITLE
New world freezing

### ISSUE THREAD

**Issue by VoidLock92** [Yoghurt4C/Flonters#5]
Hey I just updated to 1.17.1 and I am getting an error when making a new world

https://pastebin.com/7daUFZxh

Is this not compatible with 1.17.1 yet? Only 1.17?

**Comment by Yoghurt4C** [comment]
![1567440250595](https://user-images.githubusercontent.com/11313954/127560214-6d335bea-638b-4467-978f-3ec1ef859889.gif)

**Comment by Yoghurt4C** [comment]
should be fixed in https://github.com/Yoghurt4C/Flonters/commit/faf31473eb2db2723f4b3bbdd4857414cfd86cb1 ?
seems like I can't get away with ignoring static warnings anymore lol

**Comment by Yoghurt4C** [comment]
please try https://github.com/Yoghurt4C/Flonters/releases/download/v1.2.1/Flonters-1.2.1+1.17.1.jar and see if it resolves the issue on your end

**Comment by VoidLock92** [comment]
Yes this works :) Seems to be all good, it let me generate the world and after flying around a bit I am seeing the flowers now.
