### ISSUE TITLE
Flower pots with 2-height flowers replaces the above block.

### ISSUE THREAD

**Issue by acorryn** [Yoghurt4C/Flonters#6]
When placing a flower that normally takes the space of 2 blocks (rose, sunflower, lilac, peony and any tall variant flonter) into a flower pot, the block above it will be replaced with the upper half of Flonter's potted flower.

This can delete bedrock or any tile entity, as well as cause the flower & pot to be duplicated when the lower half is broken.

**Comment by Yoghurt4C** [comment]
I've identified the obvious issue but this will have to stay unfixed for the night

**Comment by Yoghurt4C** [comment]
I got stuck in a time loop but it's fixed now (as long as you're playing on the stinky memeversion known as 1.18) https://github.com/Yoghurt4C/Flonters/commit/c3c6715bae0c5a54daa396915c91092ce7109095
