### ISSUE TITLE
1.18.2 compatibility?

### ISSUE THREAD

**Issue by BrekiTomasson** [Yoghurt4C/Flonters#7]
Any news on when this'll be supported under Minecraft 1.18.2 ? Just tried running the latest released 1.8 version and it's crashing on startup.

**Comment by Yoghurt4C** [comment]
soontm, I haven't had the time to update yet

**Comment by Yoghurt4C** [comment]
hopefully addressed in https://github.com/Yoghurt4C/Flonters/commit/faf493a41a7786b3876899f338c96aeed8565380, please do tell if it's broken

**Comment by BrekiTomasson** [comment]
So far so good, looks like that solved it!
