### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by Redd56** [Yoghurt4C/Flonters#9]
that is all, get to it when you have time, no need to rush

**Comment by Yoghurt4C** [comment]
I know this will be a massive disappointment, but the possibility of getting a 1.19 version is completely nonexistent as I'd much rather make mods for versions that were made to be played by human people, such as b1.7 or 1.7.10

**Comment by Redd56** [comment]
Do i have permission to fork and continue it on my own?

**Comment by Yoghurt4C** [comment]
permission?

**Comment by Redd56** [comment]
i cant speak Japanese and the license is in Japanese, so i have no clue what the exact terms are if it was translated properly. just asking if can fork it and continue it myself

**Comment by Yoghurt4C** [comment]
why even ask THOUGH

**Comment by Redd56** [comment]
I wish to continue development on flonters on my own and not go against a license that i cant read. 
Aka i dont wanna be a dick

**Comment by Yoghurt4C** [comment]
you could just be smart and visit [bdews](https://bdew.net/minecraft-mod-public-license/)/[bc](https://mod-buildcraft.com/MMPL-1.0.txt) website, or be even smarter and disregard it completely by looking at copying.md

**Comment by Redd56** [comment]
i am fucking blind and somehow didnt see the copying.md :skull:
